name: Development Deployment Pipeline
on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

jobs:
  install:
    name: Yarn install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

  unit-test:
    name: Unit tests
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Restore yarn dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run tests
        run: CI=true yarn test:coverage

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
          flags: unittests
          verbose: true

  lint:
    name: Linting
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Restore yarn dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint

  lint-styles:
    name: Check styles
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Restore yarn dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint:styles

  types:
    name: Typecheck
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: TypeScript compile
        run: yarn types

  deploy-to-dev:
    name: Deploy to Dev
    needs: [types, lint, lint-styles, unit-test]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Restore yarn dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create public folder
        run: mkdir public

      - name: Deploy Backend
        run: yarn deploy:backend:dev --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2

      - name: Build frontend
        run: yarn build

      - name: Deploy Frontend
        run: yarn deploy:frontend:dev --require-approval never
        env:
          NODE_ENV: development
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
