name: Production deploy pipeline
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: "**/.yarn"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install

      - name: Run tests
        run: CI=true yarn test:coverage

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
          flags: unittests
          verbose: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: "**/.yarn"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn lint
